### ISSUE TITLE
how to login?

### ISSUE THREAD

**Issue by tongysh** [omegaui/chat_desk#16]
i have install the chat_desk for mac, and now start, i don't know how to login?
<img width="1200" alt="image" src="https://github.com/omegaui/chat_desk/assets/54384675/bbdf44c6-0350-43eb-8368-6a0656d6b7ca">

**Comment by omegaui** [comment]
@oucystong 
You need to grab the [`core`](https://github.com/omegaui/chat_desk_core)
Follow the complete [build instructions](https://github.com/omegaui/chat_desk_core).
